class Ile:    #Class 
    def __init__(self):
    	self.H    = None
    	self.N    = None
    	self.CA   = None
    	self.HA   = None
    	self.C    = None
    	self.O    = None
    	self.CB   = None
    	self.HB   = None
    	self.CG1  = None
        self.CG2  = None
        self.HG12 = None
        self.HG13 = None
        self.HG21 = None
        self.HG22 = None
        self.HG23 = None
        self.CD1  = None
        self.HD11 = None
        self.HD12 = None
        self.HD13 = None