class Lys:    #Class 
    def __init__(self):
    	self.H    = None
    	self.N    = None
    	self.CA   = None
    	self.HA   = None
    	self.C    = None
    	self.O    = None
    	self.CB   = None
    	self.HB2  = None
    	self.HB3  = None
        self.CG   = None
        self.HG2  = None
        self.HG3  = None
        self.CD   = None
        self.HD2  = None
        self.HD3  = None
        self.CE   = None
        self.HE2  = None
        self.HE2  = None
        self.NZ   = None
        self.HZ1  = None
        self.HZ2  = None
        self.HZ3  = None