class Met:    #Class 
    def __init__(self):
    	self.H    = None
    	self.N    = None
    	self.CA   = None
    	self.HA   = None
    	self.C    = None
    	self.O    = None
    	self.CB   = None
    	self.HB2  = None
    	self.HB3  = None
        self.CG   = None
        self.HG2  = None
        self.HG3  = None
        self.SD   = None
        self.CE   = None
        self.HE1  = None
        self.HE2  = None
        self.HE3  = None