class Phe:    #Class 
    def __init__(self):
    	self.H    = None
    	self.N    = None
    	self.CA   = None
    	self.HA   = None
    	self.C    = None
    	self.O    = None
    	self.CB   = None
    	self.HB2  = None
    	self.HB3  = None
        self.CG   = None
        self.CD1  = None
        self.CD2  = None
        self.HD1  = None
        self.HD2  = None
        self.CE1  = None
        self.CE2  = None
        self.HE1  = None
        self.HE2  = None
        self.CZ   = None
        self.HZ   = None